language: java
jdk:
  - openjdk7
language: scala
sudo: false
scala:
   - 2.11.6

script:
  # Your normal script
  - sbt ++$TRAVIS_SCALA_VERSION 'set fork in ThisBuild := false' test
  
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
