language: java
jdk:
  - oraclejdk8
language: scala
sudo: false
scala:
   - 2.11.4

sbt_args: -J-Xmx4096M -J-XX:ReservedCodeCacheSize=128m -J-XX:+UseConcMarkSweepGC -J-Djava.awt.headless=true -J-XX:NewRatio=4

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  # Your normal script
  - sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M test
  
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
