sudo: false

language: node_js
node_js:
  - "0.12"

before_install:
  - export TZ=GB
  - npm install -g grunt-cli
  - npm install -g jspm

language: java
jdk:
  - oraclejdk8

language: scala
scala:
  - 2.11.6

env:
  - APPLICATION_NAME=javascript_tests
  - APPLICATION_NAME=facia
  - APPLICATION_NAME=article
  - APPLICATION_NAME=onward
  - APPLICATION_NAME=applications
  - APPLICATION_NAME=commercial
  - APPLICATION_NAME=discussion
  - APPLICATION_NAME=rss
  - APPLICATION_NAME=sport

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - vendor

script: 
  - node -v
  - npm -v
  - npm install
  - ./node_modules/.bin/jspm registry create bower jspm-bower-endpoint -y
  - ./node_modules/.bin/jspm config registries.github.auth $JSPM_GITHUB_AUTH
  - ./node_modules/.bin/jspm registry export github
  - jspm install
  - bundle package
  - ./grunt-travis
  - ./travis.sh

  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
