language: java
jdk:
  - oraclejdk8
language: scala
sudo: false
scala:
  - 2.11.6

env:
  - APPLICATION_NAME="facia"
  - APPLICATION_NAME=article

before_install:
  - export TZ=GB

cache:
  directories:
    - node_modules
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script: 
  - npm install -g grunt-cli
  - npm install -g jspm
  - node -v
  - npm -v
  - npm install
  - bundle
  - ./grunt-travis
  - ./travis.sh

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
