language: scala
scala:
- 2.10.3
env:
  global:
  - secure: Pqq6B4cGwLUumv+3eIkSXXr1fZYWpRoIhPd8IumSdWGTzA69rx/wH14mCLFVPF2KZI66yCvTtEyH1bpeFkpky2JUcGgp26jG8qAD64ViyqDL074K23mcktUtmcEJL6jqAeQRI7CoXPyDOBnkN31/Mtc07rQPXHFSL0WbLpCCaw8=
  - secure: MoWB5mlij0gh2A4OabzmOnO5fQuZBY1O0oFISiqIzm8WG1UIKgbE6fwgrJB3znsSOpv94Tcjd0uGYz9y8J7UQeIt1HHzEGos1kNqqaQCM1Ule4m8S/ehFueP7/cEugsyo4sgedHmDSlSdM4j5HC+gfeJyTWUtqGlaWXFcUFcYgY=
  - secure: DzFAov0wA9azIrAtNpnrZBFefAMXOX7DnGa8eRL0b3lRH69sTQBX3enYYolKOecQBhQMsOAIc4gfZLZ6kU7LkCCg1cw+7mrLNIy8fLLLWPLMYGpR0+QrFxnay+WyMrVZ+T1gwdHVJENTg/NyN2pa9Kcysr61F9NCaQeBGnXewnE=
  - secure: ot06DD1CPBZ7suBJq06P0s6s5rWvVmOGzcVudR9SVMwwWdcSHgPgCDDjHviF1r+7hGrg9NeYT5rPMZXCrQM5OVxdD9Jfs/X+DEbRxBAdqccp2Z7SVlEMhSJ6Bf+q5eGR5HvJ9fFCdwkioem757UPKN72l67OYiQ3viUllVxkFx4=
  - secure: cOCU8Cj9yZEG7yR9hfZI2xvLSk1S7Xk4P6x/s/NbLbWhvhJqVwWHirnDOMbbwgZT/vrnz/Wa4O5YV1t68R5rDvh0u12TBna3L7BgRHUZsApmvuM8PPqUBtoFAB0BVQFJVYYrqs6ecn/kgMu7k9gDDVcxtrbMbGMe4ZyJtn3cPRI=
  - secure: S7HCq83qt3NiMNN9PnHDn58PHJaJ0MDtS9mx0sxjM7Yr+lBW20us7+3zXjSBojM311sFL0yEWBaiklgCNqxuAD/t9xgIcFu+vTEDznRhdOkVZwwm8L7k1D64UgA0nqTO25/+hwAd/TMXcmeRcsTUUuMbIsfHSPsostL0oJ1LpHk=
