language: java
jdk:
  - oraclejdk8
language: scala
sudo: false
scala:
  - 2.11.6

env:
  - APPLICATION_NAME="facia"
  - APPLICATION_NAME=article

script: 
  - npm install -g grunt-cli
  - npm install -g jspm
  - npm -v
  - npm install
  - bundle
  - ./grunt-tc
  - ./travis.sh
